### PR TITLE
Fixes bug in scan report 

### LINKED ISSUE #31: Nitro Scam Missed
**Describe the bug**
When nitro is excluded, tghe bot completely ignored

**To Reproduce**
1. Send a message like this:
>  `@`  everyone
> Wh\u043e is first? :)
> https://discerd.gift/FwrVcACacD
2. Observe the bot ignores it

**Expected behavior**
Bot chatches and bans the member.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

Thanks to @CasparN for catching it

### PR DESCRIPTION
**Pull request by Bluesy1**
fixes #32
closes #31

### CODE REVIEW

**Comment by Bluesy1** [comment]
Will merge once reviewed

**Comment by Bluesy1** [comment]
actually missed another issue

**Comment by Bluesy1** [comment]
actually able to reviewed now

**Review by CasparN — APPROVED** [review]
Seems good!

**Pull request merged**
